### PR TITLE
Add RUN_IN_AWS Environment Variable

### PR DESCRIPTION
**Pull request by Bourne-ID**
## Description of the change
Issue #50 - If the IMDS is rate limited/delayed/VPC CNI is delayed starting up (due to the tolerations in values.yaml) then it's possible that CloudWatch will enter an OnPremise mode instead of AWS EC2 mode, which prevents writes to the relevant log group. This PR adds a values option to enable the environment variable to force cloudwatch into AWS mode ([source](https://github.com/Cloudzero/amazon-cloudwatch-agent/blob/cf80e962899d79c1f54485f1d3158affc49d2cc1/translator/util/sdkutil.go#L36))

## Type of change
- [ ] Bug fix
- [X] New feature

### Development
- [ ] All changed code has 80% unit test coverage
- [ ] All changed code has been automatically (smoke test or otherwise) or manually verified in `alfa` (or with a cross namespace setup, e.g. developer namespace for this feature, pointing at shared `alfa` resources)

### Code review 
- [ ]  This pull request has a title that includes the ticket # and a short useful summary, e.g. `CP-4051: Create TEMPLATE Feature Repo`.

### CODE REVIEW

**Review by dmepham — CHANGES_REQUESTED** [review]
looks great, thanks for the contribution!
would you mind bumping the chart version? happy to approve after that

**Comment by Bourne-ID** [comment]
Actioned, for review :)

**Review by dmepham — APPROVED** [review]
great, thank you!

**Comment by Bourne-ID-Work** [comment]
hi @dmepham  - can I get an update on this PR's merge status? Thank you.

**Comment by dmepham** [comment]
@Bourne-ID-Work apologies, I lost track of this - merging now

**Pull request merged**
